sudo: false
os: linux
dist: trusty
compiler: clang

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
      - ubuntu-toolchain-r-test
    packages:
      - clang-4.0
      - clang-tidy-4.0
      - libwxgtk3.0-dev
      - libstdc++-5-dev

script:
  - ./travis.sh
